language: node_js
node_js: '10'
cache:
  yarn: true
  directories:
    - .firebase
    - $HOME/.npm
install: npm ci
script: npm run build
notifications:
  email: false
deploy:
  - provider: pages
    local-dir: dist
    repo: pakeweb/pakeweb.github.io
    skip-cleanup: true
    github-token: "$GITHUB_TOKEN"
    target-branch: master
    keep-history: true
    on:
      branch: master
  - provider: script
    script: npx firebase deploy --token "$FIREBASE_TOKEN"
    skip-cleanup: true
    on:
      branch: master
