language: node_js
cache:
  yarn: true
node_js: "8"
install: yarn
script: yarn build
notifications:
  email: false
deploy:
  provider: pages
  local-dir: dist
  repo: pakeweb/pakeweb.github.io
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: false
  on:
    branch: master
