language: node_js
node_js: '8'
cache:
  yarn: true
  directories:
    - .firebase
    - node_modules
before_install: yarn global add firebase-tools
install: yarn
script: yarn build
notifications:
  email: false
deploy:
  - provider: pages
    local-dir: dist
    repo: pakeweb/pakeweb.github.io
    skip-cleanup: true
    github-token: "$GITHUB_TOKEN"
    target-branch: master
    keep-history: true
    on:
      branch: master
  - provider: script
    script: firebase deploy --token "$FIREBASE_TOKEN"
    skip-cleanup: true
    on:
      branch: master
