language: node_js
node_js: '8'
cache:
  yarn: true
  directories:
    - .firebase
before_install:
  - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn
  - yarn global add firebase-tools
install: yarn --pure-lockfile
script: yarn build
notifications:
  email: false
deploy:
  - provider: pages
    local-dir: dist
    repo: pakeweb/pakeweb.github.io
    skip-cleanup: true
    github-token: "$GITHUB_TOKEN"
    target-branch: master
    keep-history: true
    on:
      branch: master
  - provider: script
    script: firebase deploy --token "$FIREBASE_TOKEN"
    skip-cleanup: true
    on:
      branch: master
